
services:
  # Frontend: Next.js
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - ./client/.env.local
    volumes:
      - ./client:/app       # mount folder lokal supaya perubahan langsung terlihat
      - /app/node_modules   # agar node_modules container tidak tertimpa

  # Backend: Express
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env.development.local      # <-- ambil variabel environment dari file .env di folder server
    volumes:
      - ./server:/app
      - /app/node_modules

